# Generated by Django 4.1.6 on 2023-03-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uis',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='colorvariant',
            old_name='uis',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='uis',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uis',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uis',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='sizevariant',
            old_name='uis',
            new_name='uid',
        ),
    ]
